# Generated by Django 5.2.3 on 2025-06-15 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SportCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter the name of the sport', max_length=100, verbose_name='name')),
                ('description', models.TextField(help_text='Describe the sport', verbose_name='description')),
                ('image', models.ImageField(blank=True, help_text='Upload an image for the sport', null=True, upload_to='sports/', verbose_name='image')),
                ('rules', models.TextField(blank=True, help_text='Enter the basic rules of the sport', verbose_name='rules')),
                ('equipment', models.TextField(blank=True, help_text='List the required equipment', verbose_name='required equipment')),
                ('popular_countries', models.CharField(blank=True, help_text='List countries where this sport is popular', max_length=255, verbose_name='popular countries')),
                ('is_olympic', models.BooleanField(default=False, help_text='Is this an Olympic sport?', verbose_name='Olympic sport')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
            ],
            options={
                'verbose_name': 'sport category',
                'verbose_name_plural': 'sport categories',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SportReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(choices=[(1, '★☆☆☆☆'), (2, '★★☆☆☆'), (3, '★★★☆☆'), (4, '★★★★☆'), (5, '★★★★★')], verbose_name='rating')),
                ('comment', models.TextField(blank=True, verbose_name='comment')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
            ],
            options={
                'verbose_name': 'review',
                'verbose_name_plural': 'reviews',
                'ordering': ['-created_at'],
            },
        ),
    ]
