# Generated by Django 5.2.3 on 2025-06-15 09:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sport_app', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sportcategory',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sports', to='sport_app.category', verbose_name='category'),
        ),
    ]
